# Generated by Django 3.0.2 on 2020-02-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/default.jpeg', upload_to='images'),
        ),
    ]
