# Generated by Django 3.0.2 on 2020-02-04 21:34

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=image_cropping.fields.ImageCropField(default='images/default.jpeg', upload_to='images'),
        ),
    ]
