# Generated by Django 3.0.2 on 2020-03-12 04:21

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200205_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cropperjs.models.CropperImageField(default='images/default.jpeg', upload_to='images'),
        ),
    ]
