# Generated by Django 3.0.2 on 2020-03-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200311_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/default.jpeg', upload_to='images'),
        ),
    ]
