# Generated by Django 2.1.5 on 2019-05-14 04:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
